BASE_URL = "https://qa-scooter.praktikum-services.ru/api/v1"
CREATE_COURIER = BASE_URL + "/courier"
LOGIN_COURIER = BASE_URL + "/courier/login"
CREATE_ORDER = BASE_URL + "/orders"
CANCEL_ORDER = BASE_URL + "/orders/cancel"
GET_ORDERS = BASE_URL + "/orders"